name: Build, test and lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  android:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@be39fa834029ff78f1a44aa3bb0819b8fc2bd8fd # v4.0.4
        with:
          packages: platform-tools
          log-accepted-android-sdk-licenses: false
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Install SDK components
        run: sdkmanager 'platforms;android-35' 'build-tools;34.0.0'
      - name: Build, test and lint
        run: ./gradlew --no-daemon testDebugUnitTest assembleDebug assembleRelease lintDebug lintRelease
